In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import seaborn as sns
from scipy import stats
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
seed=42

In [10]:
data = pd.read_csv("DataGood.csv")
data = data.drop(['NB1'], axis = 1)
data = data.drop(['NB2'], axis = 1)
data = data.drop(['CLIENTNUM'], axis = 1)

In [11]:
x = data.drop(['Attrition_Flag'], axis = 1)
y = pd.DataFrame(data['Attrition_Flag'])

categorical_columns = ['Gender', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category']
x_encoded = pd.get_dummies(x, columns=categorical_columns)


In [12]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.2, random_state=seed, shuffle=True)

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.15, random_state=seed, shuffle=True)

In [13]:
clf = LogisticRegression()
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
clf.fit(x_train_scaled, y_train)

x_val_scaled = scaler.transform(x_val)
y_hat = clf.predict(x_val_scaled)

accuracy = accuracy_score(y_val, y_hat)
confusion = confusion_matrix(y_val, y_hat)

print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(confusion)

Accuracy: 0.89
Confusion Matrix:
[[527  22]
 [ 53  69]]


C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
res = []

for C in np.logspace(start=-3, stop=3, num=10, base=10, endpoint=True):
    clf = LogisticRegression(C=C)
    scaler = StandardScaler()

    x_train_scaled = scaler.fit_transform(x_train)
    clf.fit(x_train_scaled, y_train)

    x_val_scaled = scaler.transform(x_val)
    y_hat = clf.predict(x_val_scaled)

    accuracy = accuracy_score(y_val, y_hat)
    precision = precision_score(y_val, y_hat)
    recall = recall_score(y_val, y_hat)
    f1 = f1_score(y_val, y_hat)

    print(f'{C=}, {accuracy=}, {precision=}, {recall=}, {f1=}')
    res.append({
        'C': C,
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1-score': f1
    })

C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please chang

C=0.001, accuracy=0.8256333830104322, precision=0.8571428571428571, recall=0.04918032786885246, f1=0.0930232558139535
C=0.004641588833612777, accuracy=0.8763040238450075, precision=0.9148936170212766, recall=0.3524590163934426, f1=0.5088757396449705
C=0.021544346900318832, accuracy=0.886736214605067, precision=0.8285714285714286, recall=0.47540983606557374, f1=0.6041666666666667
C=0.1, accuracy=0.8912071535022354, precision=0.788235294117647, recall=0.5491803278688525, f1=0.6473429951690821
C=0.46415888336127775, accuracy=0.8926974664679582, precision=0.7906976744186046, recall=0.5573770491803278, f1=0.6538461538461539
C=2.154434690031882, accuracy=0.8882265275707899, precision=0.7582417582417582, recall=0.5655737704918032, f1=0.6478873239436619
C=10.0, accuracy=0.8882265275707899, precision=0.7582417582417582, recall=0.5655737704918032, f1=0.6478873239436619
C=46.41588833612773, accuracy=0.8882265275707899, precision=0.7582417582417582, recall=0.5655737704918032, f1=0.6478873239436619

C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please chang

In [15]:
res_df = pd.DataFrame(res)
sorted_df = res_df.sort_values('Accuracy', ascending=False)
sorted_df

C  Accuracy  Precision    Recall  F1-score
4     0.464159  0.892697   0.790698  0.557377  0.653846
3     0.100000  0.891207   0.788235  0.549180  0.647343
5     2.154435  0.888227   0.758242  0.565574  0.647887
6    10.000000  0.888227   0.758242  0.565574  0.647887
7    46.415888  0.888227   0.758242  0.565574  0.647887
8   215.443469  0.888227   0.758242  0.565574  0.647887
9  1000.000000  0.888227   0.758242  0.565574  0.647887
2     0.021544  0.886736   0.828571  0.475410  0.604167
1     0.004642  0.876304   0.914894  0.352459  0.508876
0     0.001000  0.825633   0.857143  0.049180  0.093023

In [16]:
res_df.iloc[res_df.Accuracy.argmax()]

C            0.464159
Accuracy     0.892697
Precision    0.790698
Recall       0.557377
F1-score     0.653846
Name: 4, dtype: float64

In [17]:
C = 0.892697

In [18]:
print(f'Logistic Regression, {C=}')
clf = LogisticRegression(C=C)
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
clf.fit(x_train_scaled, y_train)

x_val_scaled = scaler.transform(x_val)
y_hat_val = clf.predict(x_val_scaled)
accuracy_val = accuracy_score(y_val, y_hat_val)
precision_val = precision_score(y_val, y_hat_val)
print(f'VAL: {accuracy_val=}, {precision_val=}')

x_test_scaled = scaler.transform(x_test)
y_hat_test = clf.predict(x_test_scaled)
accuracy_test = accuracy_score(y_test, y_hat_test)
precision_test = precision_score(y_test, y_hat_test)
print(f'TEST: {accuracy_test=}, {precision_test=}')

Logistic Regression, C=0.892697
VAL: accuracy_val=0.8897168405365127, precision_val=0.7666666666666667
TEST: accuracy_test=0.90608228980322, precision_test=0.7443609022556391


C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [19]:
confusion_val = confusion_matrix(y_val, y_hat_val)
confusion_test = confusion_matrix(y_test, y_hat_test)

In [20]:
print(confusion_val)

[[528  21]
 [ 53  69]]


In [21]:
print(confusion_test)

[[914  34]
 [ 71  99]]
